**Prediksi Pasien Penyakit Jantung dengan Klasifikasi Deep Learning**

**Import Module**

In [ ]:
import numpy as np #Mengimport numpy
import pandas as pd #Mengimport pandas
import io #Mengimport io
from sklearn.preprocessing import StandardScaler #Mengimport standarscaler
from sklearn.model_selection import train_test_split #Mengimport split train test
import warnings #Mengimport warning
warnings.filterwarnings("ignore")

**Upload file**

In [ ]:
from google.colab import files #Mengimport files
uploaded = files.upload() #Mengupload dataset

Saving heart.csv to heart.csv

**Buka file**

In [ ]:
df = pd.read_csv(io.BytesIO(uploaded['heart.csv'])) #Membaca dataset
display(df) #Menampilkan dataset

,age,sex,cp,trtbps,chol,fbs,restecg,thalachh,exng,oldpeak,slp,caa,thall,output
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

**Statistika deskriptif dari dataset**

In [ ]:
df.describe() #Melihat nilai statistika deskriptif dari tiap variabel di dataset

,age,sex,cp,trtbps,chol,fbs,restecg,thalachh,exng,oldpeak,slp,caa,thall,output
count,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000
mean,54.366337,0.683168,0.966997,131.623762,246.264026,0.148515,0.528053,149.646865,0.326733,1.039604,1.399340,0.729373,2.313531,0.544554
std,9.082101,0.466011,1.032052,17.538143,51.830751,0.356198,0.525860,22.905161,0.469794,1.161075,0.616226,1.022606,0.612277,0.498835
min,29.000000,0.000000,0.000000,94.000000,126.000000,0.000000,0.000000,71.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,47.500000,0.000000,0.000000,120.000000,211.000000,0.000000,0.000000,133.500000,0.000000,0.000000,1.000000,0.000000,2.000000,0.000000
50%,55.000000,1.000000,1.000000,130.000000,240.000000,0.000000,1.000000,153.000000,0.000000,0.800000,1.000000,0.000000,2.000000,1.000000
75%,61.000000,1.000000,2.000000,140.000000,274.500000,0.000000,1.000000,166.000000,1.000000,1.600000,2.000000,1.000000,3.000000,1.000000
max,77.000000,1.000000,3.000000,200.000000,564.000000,1.000000,2.000000,202.000000,1.000000,6.200000,2.000000,4.000000,3.000000,1.000000

**Cek missing value**

In [ ]:
df.isnull().sum() #Mengecek missing value

age         0
sex         0
cp          0
trtbps      0
chol        0
fbs         0
restecg     0
thalachh    0
exng        0
oldpeak     0
slp         0
caa         0
thall       0
output      0
dtype: int64

**Dataset Numerik**

In [ ]:
df_num = df[['age','trtbps','chol','thalachh','oldpeak']] #Membuat dataset numerik
df_num #Menampilkan dataset numerik

     age  trtbps  chol  thalachh  oldpeak
0     63     145   233       150      2.3
1     37     130   250       187      3.5
2     41     130   204       172      1.4
3     56     120   236       178      0.8
4     57     120   354       163      0.6
..   ...     ...   ...       ...      ...
298   57     140   241       123      0.2
299   45     110   264       132      1.2
300   68     144   193       141      3.4
301   57     130   131       115      1.2
302   57     130   236       174      0.0

[303 rows x 5 columns]

**Dataset Kategorik**

In [ ]:
df_cat = df[['sex','cp','fbs','restecg','exng','slp','caa','thall']] #Membuat dataset kategorik
df_cat #Menampilkan dataset kategorik

     sex  cp  fbs  restecg  exng  slp  caa  thall
0      1   3    1        0     0    0    0      1
1      1   2    0        1     0    0    0      2
2      0   1    0        0     0    2    0      2
3      1   1    0        1     0    2    0      2
4      0   0    0        1     1    2    0      2
..   ...  ..  ...      ...   ...  ...  ...    ...
298    0   0    0        1     1    1    0      3
299    1   3    0        1     0    1    0      3
300    1   0    1        1     0    1    2      3
301    1   0    0        1     1    1    1      3
302    0   1    0        0     0    1    1      2

[303 rows x 8 columns]

**Cek outliers dengan IQR**

In [ ]:
Q1 = df_num.quantile(0.25) #Menghitung Q1
Q3 = df_num.quantile(0.75) #Menghitung Q2

IQR = Q3 - Q1 #Menghitung IQR

IQR_outliers = df_num[((df_num < (Q1 - 1.5 * IQR)) |(df_num > (Q3 + 1.5 * IQR))).any(axis=1)] #Menyaring data yang memiliki outliers
IQR_outliers #Menampilkan data yang memiliki outliers

     age  trtbps  chol  thalachh  oldpeak
8     52     172   199       162      0.5
28    65     140   417       157      0.8
85    67     115   564       160      1.6
96    62     140   394       157      1.2
101   59     178   270       145      4.2
110   64     180   325       154      0.0
203   68     180   274       150      1.6
204   62     160   164       145      6.2
220   63     150   407       154      4.0
221   55     140   217       111      5.6
223   56     200   288       133      4.0
241   59     174   249       143      0.0
246   56     134   409       150      1.9
248   54     192   283       195      0.0
250   51     140   298       122      4.2
260   66     178   228       165      1.0
266   55     180   327       117      3.4
272   67     120   237        71      1.0
291   58     114   318       140      4.4

**List nama kolom dataset numerik**

In [ ]:
num_var = ['age','trtbps','chol','thalachh','oldpeak'] #Membuat list variabel dari dataset numerik

**Mencari batas bawah dan batas atas dari variabel dataset numerik**

In [ ]:
#Menghitung niai batas atas dan bawah dari tiap variabel di dataset numerik
for i in num_var: #for loop
  IQR = df_num[i].quantile(0.75) - df_num[i].quantile(0.25) #Menghitung nilai IQR
  lower_bound = df_num[i].quantile(0.25) - (1.5*IQR) #Menghitung nilai batas bawah
  upper_bound = df_num[i].quantile(0.75) + (1.5*IQR) #Menghitung batas atas
  
  print(i, ":", lower_bound, ",",  upper_bound) #Menampilkan batas atas dan batas bawah

age : 27.25 , 81.25
trtbps : 90.0 , 170.0
chol : 115.75 , 369.75
thalachh : 84.75 , 214.75
oldpeak : -2.4000000000000004 , 4.0

**Median dari tiap variabel dataset numerik**

In [ ]:
df_num.median() #Menampilkan nilai median dari variabel numerik

age          55.0
trtbps      130.0
chol        240.0
thalachh    153.0
oldpeak       0.8
dtype: float64

**Mengganti nilai outliers dengan median dari masing-masing variabel dataset numerik**

In [ ]:
df_num.loc[df_num.trtbps > 170.0 , "trtbps"] = 130 #Mengganti nilai outliers dari variabel trtbps dengan nilai median
df_num.loc[df_num.trtbps < 90.0 , "trtbps"] = 130 #Mengganti nilai outliers dari variabel trtbps dengan nilai median

df_num.loc[df_num.chol > 369.75 , "chol"] = 240 #Mengganti nilai outliers dari variabel chol dengan nilai median
df_num.loc[df_num.chol < 115.75 , "chol"] = 240 #Mengganti nilai outliers dari variabel chol dengan nilai median

df_num.loc[df_num.thalachh > 214.75 , "thalachh"] = 153 #Mengganti nilai outliers dari variabel thalachh dengan nilai median
df_num.loc[df_num.thalachh < 84.75 , "thalachh"] = 153 #Mengganti nilai outliers dari variabel thalachh dengan nilai median

df_num.loc[df_num.oldpeak > 4 , "oldpeak"] = 0.8 #Mengganti nilai outliers dari variabel oldpeak dengan nilai median
df_num.loc[df_num.oldpeak < -2.4 , "oldpeak"] = 0.8 #Mengganti nilai outliers dari variabel oldpeak dengan nilai median

**Menunjukan 10 data awal dari dataset numerik setelah tidak ada outliers**

In [ ]:
df_num.head(10) #Menampilkan 10 data awal dari dataset numerik

   age  trtbps  chol  thalachh  oldpeak
0   63     145   233       150      2.3
1   37     130   250       187      3.5
2   41     130   204       172      1.4
3   56     120   236       178      0.8
4   57     120   354       163      0.6
5   57     140   192       148      0.4
6   56     140   294       153      1.3
7   44     120   263       173      0.0
8   52     130   199       162      0.5
9   57     150   168       174      1.6

**One-hot encoder/membuat data dummy untuk variabel di dataset kategorik dan menggabungkannya dengan dataset numerik**

In [ ]:
cat_var = ['sex','cp','fbs','restecg','exng','slp','caa','thall'] #Membuat list variabel dari dataset numerik
df_cat = df_cat[cat_var] #Membaut dataset kategorik dengan nama variabel kategorik
df_cat = pd.get_dummies(df_cat,columns=cat_var) #Melakukan one-hot encoder
df = pd.concat([df_num,df['output'],df_cat],axis=1) #Menggabungkan dataet numerik dan kategorik
df #Menampilkan dataset

,age,trtbps,chol,thalachh,oldpeak,output,sex_0,sex_1,cp_0,cp_1,...,slp_2,caa_0,caa_1,caa_2,caa_3,caa_4,thall_0,thall_1,thall_2,thall_3
0,63,145,233,150,2.3,1,0,1,0,0,...,0,1,0,0,0,0,0,1,0,0
1,37,130,250,187,3.5,1,0,1,0,0,...,0,1,0,0,0,0,0,0,1,0
2,41,130,204,172,1.4,1,1,0,0,1,...,1,1,0,0,0,0,0,0,1,0
3,56,120,236,178,0.8,1,0,1,0,1,...,1,1,0,0,0,0,0,0,1,0
4,57,120,354,163,0.6,1,1,0,1,0,...,1,1,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,140,241,123,0.2,0,1,0,1,0,...,0,1,0,0,0,0,0,0,0,1
299,45,110,264,132,1.2,0,0,1,0,0,...,0,1,0,0,0,0,0,0,0,1
300,68,144,193,141,3.4,0,0,1,1,0,...,0,0,0,1,0,0,0,0,0,1
301,57,130,131,115,1.2,0,0,1,1,0,...,0,0,1,0,0,0,0,0,0,1
302,57,130,236,174,0.0,0,1,0,0,1,...,0,0,1,0,0,0,0,0,1,0

**Menentukan X sebagai variabel prediktor dan y sebagai variabel target**

In [ ]:
X = df.drop(['output'], axis = 1) #X sebagai variabel prediktor
y = df.output.values #y sebagai variabel target

**Membagi dataset menjadi data test dan train dengan rasio 2:8**

In [ ]:
from sklearn.model_selection import train_test_split #Mengimport split train test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0) #Membagi dataset menjadi data train dan data test

**Standarisasi dataset**

In [ ]:
from sklearn.preprocessing import StandardScaler #Mengimport standarscaler
sc = StandardScaler() #standarscaler
X_train = sc.fit_transform(X_train) #Menstandarisasi dataset x_train
X_test = sc.transform(X_test) #Menstandarisasi dataset x_test

**Menunjukkan ukuran dari dataset X_train/test dan y_train/test**

In [ ]:
print(X_train.shape) #Menampilkan ukuran dataset x_train
print(X_test.shape) #Menampilkan ukuran dataset x_test
print(y_train.shape) #Menampilkan ukuran dataset y_train
print(y_test.shape) #Menampilkan ukuran dataset x_test

(242, 30)
(61, 30)
(242,)
(61,)

**Mengimport module dan menginstall keras tuner**

In [ ]:
import numpy as np #Mengimport numpy
import keras #Mengimpoort keras
import tensorflow as tf #Mengimport tenserflow
!pip install -q -U keras-tuner #Menginstall keras tuner

import keras_tuner as kt #Mengimport keras tuner

     |████████████████████████████████| 133 kB 4.4 MB/s

**Membagi data train dan data validasi**

In [ ]:
X_valid, X_train = X_train[:70], X_train[70:] #Membagi dataset x_train dan x_valid
y_valid, y_train = y_train[:70], y_train[70:] #Membagi datase y_train dan y_valid

**Membuat model klasifikasi dengan DNN**

In [ ]:
def build_model(hp): #Membuat fungsi model DNN
  model = keras.models.Sequential() #Membuat model DNN

  model.add(Dense(32, input_dim=30, activation="relu")) #layer pertama/input layer
  hp_layers = hp.Choice('layer', [3,4])  #jumlah layer
  hp_neurons = hp.Int('neuron', min_value = 10, max_value=100, step = 10)  #Jumlah neuron

  for layer in range(hp_layers): #for loop
    model.add(keras.layers.Dense(hp_neurons, activation = 'relu'))  #jumlah hidden layers

  model.add(keras.layers.Dense(2, activation = 'softmax'))  #layer terakhir/output layer
  optimizer = tf.keras.optimizers.Adam() #memasukan optimizer
  model.compile(optimizer='adam',loss = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True), metrics=['accuracy']) #meng-compile model DNN
    
  return model #Mengembalikan model DNN

**Hyperparameter tuning untuk model klasifikasi DNN**

In [ ]:
from keras.layers import Dense #Mengimport dense
tuner = kt.Hyperband(build_model, objective = 'val_accuracy',max_epochs = 10, directory = 'my_dir', project_name = 'my_tuner')

#early stopping
stop_early = tf.keras.callbacks.EarlyStopping(monitor = 'val_loss',patience = 5)
#proses pencarian hyperparameter terbaik
tuner.search(X_train, y_train, epochs = 100, validation_data = [X_valid, y_valid], callbacks = [stop_early])

Trial 27 Complete [00h 00m 01s]
val_accuracy: 0.8285714387893677

Best val_accuracy So Far: 0.8285714387893677
Total elapsed time: 00h 00m 55s
INFO:tensorflow:Oracle triggered exit

**Menampilkan jumlah layers dan neurons terbaik**

In [ ]:
best_hps=tuner.get_best_hyperparameters()[0] #Mengambil hyperparameter terbaik

print('best number of layers:',best_hps.get('layer')) #Menampilkan jumlah layers terbaik
print('best number of neurons:',best_hps.get('neuron')) #Menampilkan jumlah neuron terbaik

best number of layers: 3
best number of neurons: 70

**Menjalankan model dengan parameter hasil dari hyperparameter tuning**

In [ ]:
model = tuner.hypermodel.build(best_hps) #Menjalankan model kalsifiksi DNN

**Fitting model**

In [ ]:
model.fit(X_train, y_train, epochs = 200, batch_size = 100,validation_split= 0.2) #Fitting model DNN

Epoch 1/200
2/2 [==============================] - 1s 189ms/step - loss: 0.7080 - accuracy: 0.5839 - val_loss: 0.7530 - val_accuracy: 0.4857
Epoch 2/200
2/2 [==============================] - 0s 27ms/step - loss: 0.6600 - accuracy: 0.5985 - val_loss: 0.7151 - val_accuracy: 0.5143
Epoch 3/200
2/2 [==============================] - 0s 30ms/step - loss: 0.6226 - accuracy: 0.6204 - val_loss: 0.6830 - val_accuracy: 0.6286
Epoch 4/200
2/2 [==============================] - 0s 26ms/step - loss: 0.5870 - accuracy: 0.7080 - val_loss: 0.6539 - val_accuracy: 0.6571
Epoch 5/200
2/2 [==============================] - 0s 31ms/step - loss: 0.5529 - accuracy: 0.7737 - val_loss: 0.6237 - val_accuracy: 0.6857
Epoch 6/200
2/2 [==============================] - 0s 31ms/step - loss: 0.5151 - accuracy: 0.8394 - val_loss: 0.5972 - val_accuracy: 0.7143
Epoch 7/200
2/2 [==============================] - 0s 46ms/step - loss: 0.4785 - accuracy: 0.8467 - val_loss: 0.5775 - val_accuracy: 0.7429
Epoch 8/200
2/2 [==============================] - 0s 40ms/step - loss: 0.4412 - accuracy: 0.8467 - val_loss: 0.5682 - val_accuracy: 0.7429
Epoch 9/200
2/2 [==============================] - 0s 40ms/step - loss: 0.4063 - accuracy: 0.8540 - val_loss: 0.5647 - val_accuracy: 0.7429
Epoch 10/200
2/2 [==============================] - 0s 46ms/step - loss: 0.3771 - accuracy: 0.8686 - val_loss: 0.5583 - val_accuracy: 0.7429
Epoch 11/200
2/2 [==============================] - 0s 39ms/step - loss: 0.3459 - accuracy: 0.8759 - val_loss: 0.5412 - val_accuracy: 0.7714
Epoch 12/200
2/2 [==============================] - 0s 40ms/step - loss: 0.3191 - accuracy: 0.8832 - val_loss: 0.5204 - val_accuracy: 0.8000
Epoch 13/200
2/2 [==============================] - 0s 44ms/step - loss: 0.2906 - accuracy: 0.9051 - val_loss: 0.5030 - val_accuracy: 0.8000
Epoch 14/200
2/2 [==============================] - 0s 44ms/step - loss: 0.2680 - accuracy: 0.9124 - val_loss: 0.4919 - val_accuracy: 0.8286
Epoch 15/200
2/2 [==============================] - 0s 43ms/step - loss: 0.2469 - accuracy: 0.9124 - val_loss: 0.4914 - val_accuracy: 0.8286
Epoch 16/200
2/2 [==============================] - 0s 75ms/step - loss: 0.2302 - accuracy: 0.9124 - val_loss: 0.5001 - val_accuracy: 0.8286
Epoch 17/200
2/2 [==============================] - 0s 113ms/step - loss: 0.2136 - accuracy: 0.9197 - val_loss: 0.5227 - val_accuracy: 0.8286
Epoch 18/200
2/2 [==============================] - 0s 38ms/step - loss: 0.1976 - accuracy: 0.9197 - val_loss: 0.5613 - val_accuracy: 0.8286
Epoch 19/200
2/2 [==============================] - 0s 39ms/step - loss: 0.1853 - accuracy: 0.9270 - val_loss: 0.6028 - val_accuracy: 0.8000
Epoch 20/200
2/2 [==============================] - 0s 48ms/step - loss: 0.1741 - accuracy: 0.9270 - val_loss: 0.6273 - val_accuracy: 0.8000
Epoch 21/200
2/2 [==============================] - 0s 41ms/step - loss: 0.1615 - accuracy: 0.9416 - val_loss: 0.6229 - val_accuracy: 0.8286
Epoch 22/200
2/2 [==============================] - 0s 44ms/step - loss: 0.1493 - accuracy: 0.9489 - val_loss: 0.6179 - val_accuracy: 0.8286
Epoch 23/200
2/2 [==============================] - 0s 32ms/step - loss: 0.1364 - accuracy: 0.9562 - val_loss: 0.6251 - val_accuracy: 0.8571
Epoch 24/200
2/2 [==============================] - 0s 28ms/step - loss: 0.1260 - accuracy: 0.9635 - val_loss: 0.6430 - val_accuracy: 0.8571
Epoch 25/200
2/2 [==============================] - 0s 30ms/step - loss: 0.1170 - accuracy: 0.9635 - val_loss: 0.6629 - val_accuracy: 0.8571
Epoch 26/200
2/2 [==============================] - 0s 27ms/step - loss: 0.1079 - accuracy: 0.9708 - val_loss: 0.6836 - val_accuracy: 0.8571
Epoch 27/200
2/2 [==============================] - 0s 29ms/step - loss: 0.0999 - accuracy: 0.9781 - val_loss: 0.7146 - val_accuracy: 0.8571
Epoch 28/200
2/2 [==============================] - 0s 28ms/step - loss: 0.0921 - accuracy: 0.9781 - val_loss: 0.7392 - val_accuracy: 0.8571
Epoch 29/200
2/2 [==============================] - 0s 27ms/step - loss: 0.0856 - accuracy: 0.9927 - val_loss: 0.7628 - val_accuracy: 0.8571
Epoch 30/200
2/2 [==============================] - 0s 29ms/step - loss: 0.0797 - accuracy: 0.9927 - val_loss: 0.7834 - val_accuracy: 0.8286
Epoch 31/200
2/2 [==============================] - 0s 27ms/step - loss: 0.0743 - accuracy: 0.9927 - val_loss: 0.7960 - val_accuracy: 0.8286
Epoch 32/200
2/2 [==============================] - 0s 29ms/step - loss: 0.0683 - accuracy: 0.9927 - val_loss: 0.7886 - val_accuracy: 0.8571
Epoch 33/200
2/2 [==============================] - 0s 29ms/step - loss: 0.0615 - accuracy: 0.9927 - val_loss: 0.7899 - val_accuracy: 0.8571
Epoch 34/200
2/2 [==============================] - 0s 33ms/step - loss: 0.0551 - accuracy: 0.9927 - val_loss: 0.7958 - val_accuracy: 0.8571
Epoch 35/200
2/2 [==============================] - 0s 31ms/step - loss: 0.0502 - accuracy: 0.9927 - val_loss: 0.7988 - val_accuracy: 0.8286
Epoch 36/200
2/2 [==============================] - 0s 30ms/step - loss: 0.0467 - accuracy: 0.9927 - val_loss: 0.8046 - val_accuracy: 0.8000
Epoch 37/200
2/2 [==============================] - 0s 40ms/step - loss: 0.0418 - accuracy: 0.9927 - val_loss: 0.8154 - val_accuracy: 0.8000
Epoch 38/200
2/2 [==============================] - 0s 42ms/step - loss: 0.0384 - accuracy: 0.9927 - val_loss: 0.8233 - val_accuracy: 0.8000
Epoch 39/200
2/2 [==============================] - 0s 39ms/step - loss: 0.0344 - accuracy: 0.9927 - val_loss: 0.8350 - val_accuracy: 0.8000
Epoch 40/200
2/2 [==============================] - 0s 29ms/step - loss: 0.0315 - accuracy: 0.9927 - val_loss: 0.8500 - val_accuracy: 0.8000
Epoch 41/200
2/2 [==============================] - 0s 34ms/step - loss: 0.0282 - accuracy: 0.9927 - val_loss: 0.8794 - val_accuracy: 0.8286
Epoch 42/200
2/2 [==============================] - 0s 30ms/step - loss: 0.0253 - accuracy: 0.9927 - val_loss: 0.9111 - val_accuracy: 0.8286
Epoch 43/200
2/2 [==============================] - 0s 27ms/step - loss: 0.0231 - accuracy: 0.9927 - val_loss: 0.9357 - val_accuracy: 0.8286
Epoch 44/200
2/2 [==============================] - 0s 31ms/step - loss: 0.0211 - accuracy: 0.9927 - val_loss: 0.9456 - val_accuracy: 0.8286
Epoch 45/200
2/2 [==============================] - 0s 28ms/step - loss: 0.0187 - accuracy: 0.9927 - val_loss: 0.9511 - val_accuracy: 0.8000
Epoch 46/200
2/2 [==============================] - 0s 29ms/step - loss: 0.0173 - accuracy: 0.9927 - val_loss: 0.9564 - val_accuracy: 0.8286
Epoch 47/200
2/2 [==============================] - 0s 29ms/step - loss: 0.0156 - accuracy: 0.9927 - val_loss: 0.9711 - val_accuracy: 0.8286
Epoch 48/200
2/2 [==============================] - 0s 28ms/step - loss: 0.0142 - accuracy: 1.0000 - val_loss: 0.9920 - val_accuracy: 0.8286
Epoch 49/200
2/2 [==============================] - 0s 29ms/step - loss: 0.0127 - accuracy: 1.0000 - val_loss: 1.0158 - val_accuracy: 0.8286
Epoch 50/200
2/2 [==============================] - 0s 38ms/step - loss: 0.0116 - accuracy: 1.0000 - val_loss: 1.0425 - val_accuracy: 0.8000
Epoch 51/200
2/2 [==============================] - 0s 35ms/step - loss: 0.0107 - accuracy: 1.0000 - val_loss: 1.0651 - val_accuracy: 0.8000
Epoch 52/200
2/2 [==============================] - 0s 28ms/step - loss: 0.0098 - accuracy: 1.0000 - val_loss: 1.0780 - val_accuracy: 0.8000
Epoch 53/200
2/2 [==============================] - 0s 32ms/step - loss: 0.0088 - accuracy: 1.0000 - val_loss: 1.0917 - val_accuracy: 0.8000
Epoch 54/200
2/2 [==============================] - 0s 32ms/step - loss: 0.0080 - accuracy: 1.0000 - val_loss: 1.1032 - val_accuracy: 0.8000
Epoch 55/200
2/2 [==============================] - 0s 36ms/step - loss: 0.0073 - accuracy: 1.0000 - val_loss: 1.1163 - val_accuracy: 0.8000
Epoch 56/200
2/2 [==============================] - 0s 31ms/step - loss: 0.0066 - accuracy: 1.0000 - val_loss: 1.1313 - val_accuracy: 0.8000
Epoch 57/200
2/2 [==============================] - 0s 27ms/step - loss: 0.0060 - accuracy: 1.0000 - val_loss: 1.1395 - val_accuracy: 0.8000
Epoch 58/200
2/2 [==============================] - 0s 31ms/step - loss: 0.0055 - accuracy: 1.0000 - val_loss: 1.1429 - val_accuracy: 0.8286
Epoch 59/200
2/2 [==============================] - 0s 31ms/step - loss: 0.0051 - accuracy: 1.0000 - val_loss: 1.1485 - val_accuracy: 0.8286
Epoch 60/200
2/2 [==============================] - 0s 40ms/step - loss: 0.0046 - accuracy: 1.0000 - val_loss: 1.1560 - val_accuracy: 0.8286
Epoch 61/200
2/2 [==============================] - 0s 51ms/step - loss: 0.0043 - accuracy: 1.0000 - val_loss: 1.1617 - val_accuracy: 0.8286
Epoch 62/200
2/2 [==============================] - 0s 47ms/step - loss: 0.0040 - accuracy: 1.0000 - val_loss: 1.1728 - val_accuracy: 0.8286
Epoch 63/200
2/2 [==============================] - 0s 45ms/step - loss: 0.0036 - accuracy: 1.0000 - val_loss: 1.1877 - val_accuracy: 0.8286
Epoch 64/200
2/2 [==============================] - 0s 43ms/step - loss: 0.0034 - accuracy: 1.0000 - val_loss: 1.2044 - val_accuracy: 0.8286
Epoch 65/200
2/2 [==============================] - 0s 45ms/step - loss: 0.0032 - accuracy: 1.0000 - val_loss: 1.2211 - val_accuracy: 0.8286
Epoch 66/200
2/2 [==============================] - 0s 49ms/step - loss: 0.0030 - accuracy: 1.0000 - val_loss: 1.2364 - val_accuracy: 0.8286
Epoch 67/200
2/2 [==============================] - 0s 40ms/step - loss: 0.0029 - accuracy: 1.0000 - val_loss: 1.2477 - val_accuracy: 0.8286
Epoch 68/200
2/2 [==============================] - 0s 30ms/step - loss: 0.0027 - accuracy: 1.0000 - val_loss: 1.2528 - val_accuracy: 0.8286
Epoch 69/200
2/2 [==============================] - 0s 32ms/step - loss: 0.0025 - accuracy: 1.0000 - val_loss: 1.2531 - val_accuracy: 0.8286
Epoch 70/200
2/2 [==============================] - 0s 30ms/step - loss: 0.0023 - accuracy: 1.0000 - val_loss: 1.2549 - val_accuracy: 0.8286
Epoch 71/200
2/2 [==============================] - 0s 32ms/step - loss: 0.0022 - accuracy: 1.0000 - val_loss: 1.2601 - val_accuracy: 0.8286
Epoch 72/200
2/2 [==============================] - 0s 34ms/step - loss: 0.0020 - accuracy: 1.0000 - val_loss: 1.2663 - val_accuracy: 0.8286
Epoch 73/200
2/2 [==============================] - 0s 30ms/step - loss: 0.0019 - accuracy: 1.0000 - val_loss: 1.2718 - val_accuracy: 0.8286
Epoch 74/200
2/2 [==============================] - 0s 32ms/step - loss: 0.0018 - accuracy: 1.0000 - val_loss: 1.2771 - val_accuracy: 0.8286
Epoch 75/200
2/2 [==============================] - 0s 27ms/step - loss: 0.0018 - accuracy: 1.0000 - val_loss: 1.2833 - val_accuracy: 0.8286
Epoch 76/200
2/2 [==============================] - 0s 37ms/step - loss: 0.0017 - accuracy: 1.0000 - val_loss: 1.2917 - val_accuracy: 0.8286
Epoch 77/200
2/2 [==============================] - 0s 32ms/step - loss: 0.0016 - accuracy: 1.0000 - val_loss: 1.3017 - val_accuracy: 0.8286
Epoch 78/200
2/2 [==============================] - 0s 32ms/step - loss: 0.0015 - accuracy: 1.0000 - val_loss: 1.3120 - val_accuracy: 0.8286
Epoch 79/200
2/2 [==============================] - 0s 47ms/step - loss: 0.0015 - accuracy: 1.0000 - val_loss: 1.3212 - val_accuracy: 0.8286
Epoch 80/200
2/2 [==============================] - 0s 36ms/step - loss: 0.0014 - accuracy: 1.0000 - val_loss: 1.3287 - val_accuracy: 0.8286
Epoch 81/200
2/2 [==============================] - 0s 28ms/step - loss: 0.0013 - accuracy: 1.0000 - val_loss: 1.3358 - val_accuracy: 0.8286
Epoch 82/200
2/2 [==============================] - 0s 34ms/step - loss: 0.0013 - accuracy: 1.0000 - val_loss: 1.3431 - val_accuracy: 0.8286
Epoch 83/200
2/2 [==============================] - 0s 30ms/step - loss: 0.0012 - accuracy: 1.0000 - val_loss: 1.3505 - val_accuracy: 0.8286
Epoch 84/200
2/2 [==============================] - 0s 28ms/step - loss: 0.0012 - accuracy: 1.0000 - val_loss: 1.3574 - val_accuracy: 0.8286
Epoch 85/200
2/2 [==============================] - 0s 31ms/step - loss: 0.0011 - accuracy: 1.0000 - val_loss: 1.3641 - val_accuracy: 0.8286
Epoch 86/200
2/2 [==============================] - 0s 28ms/step - loss: 0.0011 - accuracy: 1.0000 - val_loss: 1.3706 - val_accuracy: 0.8286
Epoch 87/200
2/2 [==============================] - 0s 29ms/step - loss: 0.0011 - accuracy: 1.0000 - val_loss: 1.3781 - val_accuracy: 0.8286
Epoch 88/200
2/2 [==============================] - 0s 32ms/step - loss: 0.0010 - accuracy: 1.0000 - val_loss: 1.3863 - val_accuracy: 0.8286
Epoch 89/200
2/2 [==============================] - 0s 29ms/step - loss: 0.0010 - accuracy: 1.0000 - val_loss: 1.3932 - val_accuracy: 0.8286
Epoch 90/200
2/2 [==============================] - 0s 30ms/step - loss: 9.6247e-04 - accuracy: 1.0000 - val_loss: 1.3964 - val_accuracy: 0.8286
Epoch 91/200
2/2 [==============================] - 0s 28ms/step - loss: 9.2878e-04 - accuracy: 1.0000 - val_loss: 1.3997 - val_accuracy: 0.8286
Epoch 92/200
2/2 [==============================] - 0s 41ms/step - loss: 9.0107e-04 - accuracy: 1.0000 - val_loss: 1.4038 - val_accuracy: 0.8286
Epoch 93/200
2/2 [==============================] - 0s 37ms/step - loss: 8.7156e-04 - accuracy: 1.0000 - val_loss: 1.4089 - val_accuracy: 0.8286
Epoch 94/200
2/2 [==============================] - 0s 29ms/step - loss: 8.4332e-04 - accuracy: 1.0000 - val_loss: 1.4126 - val_accuracy: 0.8286
Epoch 95/200
2/2 [==============================] - 0s 32ms/step - loss: 8.1307e-04 - accuracy: 1.0000 - val_loss: 1.4170 - val_accuracy: 0.8286
Epoch 96/200
2/2 [==============================] - 0s 35ms/step - loss: 7.8937e-04 - accuracy: 1.0000 - val_loss: 1.4207 - val_accuracy: 0.8286
Epoch 97/200
2/2 [==============================] - 0s 33ms/step - loss: 7.6313e-04 - accuracy: 1.0000 - val_loss: 1.4250 - val_accuracy: 0.8286
Epoch 98/200
2/2 [==============================] - 0s 34ms/step - loss: 7.3815e-04 - accuracy: 1.0000 - val_loss: 1.4300 - val_accuracy: 0.8286
Epoch 99/200
2/2 [==============================] - 0s 35ms/step - loss: 7.1772e-04 - accuracy: 1.0000 - val_loss: 1.4342 - val_accuracy: 0.8286
Epoch 100/200
2/2 [==============================] - 0s 30ms/step - loss: 6.9526e-04 - accuracy: 1.0000 - val_loss: 1.4388 - val_accuracy: 0.8286
Epoch 101/200
2/2 [==============================] - 0s 32ms/step - loss: 6.7429e-04 - accuracy: 1.0000 - val_loss: 1.4439 - val_accuracy: 0.8286
Epoch 102/200
2/2 [==============================] - 0s 27ms/step - loss: 6.5636e-04 - accuracy: 1.0000 - val_loss: 1.4487 - val_accuracy: 0.8286
Epoch 103/200
2/2 [==============================] - 0s 27ms/step - loss: 6.3358e-04 - accuracy: 1.0000 - val_loss: 1.4519 - val_accuracy: 0.8286
Epoch 104/200
2/2 [==============================] - 0s 30ms/step - loss: 6.2030e-04 - accuracy: 1.0000 - val_loss: 1.4548 - val_accuracy: 0.8286
Epoch 105/200
2/2 [==============================] - 0s 30ms/step - loss: 6.0167e-04 - accuracy: 1.0000 - val_loss: 1.4586 - val_accuracy: 0.8286
Epoch 106/200
2/2 [==============================] - 0s 37ms/step - loss: 5.8141e-04 - accuracy: 1.0000 - val_loss: 1.4627 - val_accuracy: 0.8286
Epoch 107/200
2/2 [==============================] - 0s 30ms/step - loss: 5.6578e-04 - accuracy: 1.0000 - val_loss: 1.4663 - val_accuracy: 0.8286
Epoch 108/200
2/2 [==============================] - 0s 29ms/step - loss: 5.5024e-04 - accuracy: 1.0000 - val_loss: 1.4700 - val_accuracy: 0.8286
Epoch 109/200
2/2 [==============================] - 0s 31ms/step - loss: 5.3294e-04 - accuracy: 1.0000 - val_loss: 1.4723 - val_accuracy: 0.8286
Epoch 110/200
2/2 [==============================] - 0s 29ms/step - loss: 5.1920e-04 - accuracy: 1.0000 - val_loss: 1.4758 - val_accuracy: 0.8286
Epoch 111/200
2/2 [==============================] - 0s 32ms/step - loss: 5.0253e-04 - accuracy: 1.0000 - val_loss: 1.4803 - val_accuracy: 0.8286
Epoch 112/200
2/2 [==============================] - 0s 32ms/step - loss: 4.8996e-04 - accuracy: 1.0000 - val_loss: 1.4843 - val_accuracy: 0.8286
Epoch 113/200
2/2 [==============================] - 0s 33ms/step - loss: 4.7698e-04 - accuracy: 1.0000 - val_loss: 1.4885 - val_accuracy: 0.8286
Epoch 114/200
2/2 [==============================] - 0s 29ms/step - loss: 4.6479e-04 - accuracy: 1.0000 - val_loss: 1.4929 - val_accuracy: 0.8286
Epoch 115/200
2/2 [==============================] - 0s 29ms/step - loss: 4.5174e-04 - accuracy: 1.0000 - val_loss: 1.4966 - val_accuracy: 0.8286
Epoch 116/200
2/2 [==============================] - 0s 32ms/step - loss: 4.4116e-04 - accuracy: 1.0000 - val_loss: 1.4992 - val_accuracy: 0.8286
Epoch 117/200
2/2 [==============================] - 0s 32ms/step - loss: 4.3177e-04 - accuracy: 1.0000 - val_loss: 1.5022 - val_accuracy: 0.8286
Epoch 118/200
2/2 [==============================] - 0s 32ms/step - loss: 4.2138e-04 - accuracy: 1.0000 - val_loss: 1.5067 - val_accuracy: 0.8286
Epoch 119/200
2/2 [==============================] - 0s 35ms/step - loss: 4.1181e-04 - accuracy: 1.0000 - val_loss: 1.5111 - val_accuracy: 0.8286
Epoch 120/200
2/2 [==============================] - 0s 27ms/step - loss: 4.0386e-04 - accuracy: 1.0000 - val_loss: 1.5152 - val_accuracy: 0.8286
Epoch 121/200
2/2 [==============================] - 0s 44ms/step - loss: 3.9563e-04 - accuracy: 1.0000 - val_loss: 1.5189 - val_accuracy: 0.8286
Epoch 122/200
2/2 [==============================] - 0s 121ms/step - loss: 3.8746e-04 - accuracy: 1.0000 - val_loss: 1.5226 - val_accuracy: 0.8286
Epoch 123/200
2/2 [==============================] - 0s 61ms/step - loss: 3.7930e-04 - accuracy: 1.0000 - val_loss: 1.5263 - val_accuracy: 0.8286
Epoch 124/200
2/2 [==============================] - 0s 46ms/step - loss: 3.7170e-04 - accuracy: 1.0000 - val_loss: 1.5300 - val_accuracy: 0.8286
Epoch 125/200
2/2 [==============================] - 0s 51ms/step - loss: 3.6464e-04 - accuracy: 1.0000 - val_loss: 1.5334 - val_accuracy: 0.8286
Epoch 126/200
2/2 [==============================] - 0s 55ms/step - loss: 3.5708e-04 - accuracy: 1.0000 - val_loss: 1.5366 - val_accuracy: 0.8286
Epoch 127/200
2/2 [==============================] - 0s 57ms/step - loss: 3.4982e-04 - accuracy: 1.0000 - val_loss: 1.5398 - val_accuracy: 0.8286
Epoch 128/200
2/2 [==============================] - 0s 43ms/step - loss: 3.4343e-04 - accuracy: 1.0000 - val_loss: 1.5430 - val_accuracy: 0.8286
Epoch 129/200
2/2 [==============================] - 0s 49ms/step - loss: 3.3707e-04 - accuracy: 1.0000 - val_loss: 1.5456 - val_accuracy: 0.8286
Epoch 130/200
2/2 [==============================] - 0s 44ms/step - loss: 3.3101e-04 - accuracy: 1.0000 - val_loss: 1.5481 - val_accuracy: 0.8286
Epoch 131/200
2/2 [==============================] - 0s 54ms/step - loss: 3.2525e-04 - accuracy: 1.0000 - val_loss: 1.5510 - val_accuracy: 0.8286
Epoch 132/200
2/2 [==============================] - 0s 47ms/step - loss: 3.1940e-04 - accuracy: 1.0000 - val_loss: 1.5532 - val_accuracy: 0.8286
Epoch 133/200
2/2 [==============================] - 0s 44ms/step - loss: 3.1373e-04 - accuracy: 1.0000 - val_loss: 1.5546 - val_accuracy: 0.8286
Epoch 134/200
2/2 [==============================] - 0s 40ms/step - loss: 3.0743e-04 - accuracy: 1.0000 - val_loss: 1.5569 - val_accuracy: 0.8286
Epoch 135/200
2/2 [==============================] - 0s 48ms/step - loss: 3.0117e-04 - accuracy: 1.0000 - val_loss: 1.5593 - val_accuracy: 0.8286
Epoch 136/200
2/2 [==============================] - 0s 50ms/step - loss: 2.9660e-04 - accuracy: 1.0000 - val_loss: 1.5619 - val_accuracy: 0.8286
Epoch 137/200
2/2 [==============================] - 0s 43ms/step - loss: 2.9029e-04 - accuracy: 1.0000 - val_loss: 1.5654 - val_accuracy: 0.8286
Epoch 138/200
2/2 [==============================] - 0s 54ms/step - loss: 2.8428e-04 - accuracy: 1.0000 - val_loss: 1.5684 - val_accuracy: 0.8286
Epoch 139/200
2/2 [==============================] - 0s 60ms/step - loss: 2.7884e-04 - accuracy: 1.0000 - val_loss: 1.5706 - val_accuracy: 0.8286
Epoch 140/200
2/2 [==============================] - 0s 45ms/step - loss: 2.7258e-04 - accuracy: 1.0000 - val_loss: 1.5735 - val_accuracy: 0.8286
Epoch 141/200

**Melakukan prediksi klasifikasi DNN**

In [ ]:
ypred=model.predict(X_test) #Melakukan prediksi 
ypred #Menampilkan hasil prediksi

array([[1.00000000e+00, 4.29622865e-10],
       [2.04418182e-01, 7.95581758e-01],
       [9.79294896e-01, 2.07050461e-02],
       [1.00000000e+00, 4.94825708e-11],
       [1.00000000e+00, 2.92790209e-10],
       [9.99987364e-01, 1.26674940e-05],
       [9.99974370e-01, 2.56348012e-05],
       [1.00000000e+00, 2.38987674e-09],
       [1.00000000e+00, 1.46320911e-12],
       [1.00000000e+00, 1.70831611e-13],
       [1.48871904e-09, 1.00000000e+00],
       [2.40511980e-07, 9.99999762e-01],
       [1.00000000e+00, 3.92475719e-10],
       [2.26676917e-07, 9.99999762e-01],
       [1.36585044e-07, 9.99999881e-01],
       [2.73181999e-04, 9.99726832e-01],
       [9.99992609e-01, 7.36393486e-06],
       [1.43481477e-04, 9.99856472e-01],
       [9.99999762e-01, 2.68547069e-07],
       [1.46855790e-08, 1.00000000e+00],
       [1.02175334e-02, 9.89782453e-01],
       [9.99917269e-01, 8.26964315e-05],
       [9.99991655e-01, 8.32674505e-06],
       [9.12755966e-01, 8.72440487e-02],
       [1.12450255e-06, 9.99998927e-01],
       [7.68105388e-02, 9.23189461e-01],
       [1.51446375e-05, 9.99984860e-01],
       [9.98099148e-01, 1.90090400e-03],
       [3.50112850e-09, 1.00000000e+00],
       [4.22680052e-03, 9.95773256e-01],
       [3.91925545e-03, 9.96080816e-01],
       [1.00000000e+00, 8.95710264e-13],
       [9.12297171e-09, 1.00000000e+00],
       [3.84578243e-07, 9.99999642e-01],
       [2.59785281e-07, 9.99999762e-01],
       [8.97825122e-01, 1.02174945e-01],
       [1.00000000e+00, 4.78845186e-09],
       [3.74484807e-06, 9.99996305e-01],
       [9.99999285e-01, 7.65129812e-07],
       [9.99996305e-01, 3.70485691e-06],
       [1.40593303e-02, 9.85940695e-01],
       [7.91397997e-06, 9.99992132e-01],
       [1.29062023e-08, 1.00000000e+00],
       [9.99987006e-01, 1.30473945e-05],
       [2.55689263e-01, 7.44310737e-01],
       [8.41578824e-08, 9.99999881e-01],
       [4.18662821e-05, 9.99958158e-01],
       [9.99011636e-01, 9.88372718e-04],
       [9.99998569e-01, 1.41393923e-06],
       [3.65432271e-07, 9.99999642e-01],
       [1.05214099e-07, 9.99999881e-01],
       [1.86565321e-05, 9.99981284e-01],
       [2.48971588e-07, 9.99999762e-01],
       [7.72111161e-06, 9.99992251e-01],
       [3.10033954e-07, 9.99999642e-01],
       [9.99978662e-01, 2.13724306e-05],
       [9.59614863e-06, 9.99990463e-01],
       [1.11992085e-06, 9.99998927e-01],
       [8.77557159e-06, 9.99991179e-01],
       [3.11348884e-08, 1.00000000e+00],
       [1.37489303e-06, 9.99998569e-01]], dtype=float32)

**Mengembalikan indeks elemen maks dari suatu kolom/baris tertentu**

In [ ]:
y_pred=np.array([np.argmax(i) for i in ypred]) #Mengembalikan indeks elemen maks

**Evaluasi model**

In [ ]:
from sklearn.metrics import classification_report, accuracy_score #Mengimport klasifikasi report dan skor akurasi
print('Results for Binary Model') #Menampilkan tulisan hasil
print(accuracy_score(y_test, y_pred)) #Menampilkan skor akurasi
print(classification_report(y_test, y_pred)) #Menampilkan klasifikasi report

Results for Binary Model
0.9016393442622951
              precision    recall  f1-score   support

           0       0.92      0.85      0.88        27
           1       0.89      0.94      0.91        34

    accuracy                           0.90        61
   macro avg       0.90      0.90      0.90        61
weighted avg       0.90      0.90      0.90        61

Program ini adalah program klasifikasi DNN untuk memprediksi pasien yang mengidap serangan jantung

Ide nya adalah memprediksi dari beberapa faktor apakah seorang pasien terkena penyakit jantung. 

Algoritma

1. Menginput dataset
2. Melakukan pengecekan mssing value
3. Memisahkan data numerik dan kategorik
4. Melakukan pengecekan outliers
5. Melakukan penggantian nilai outliers dengan median
6. Melakukan one-hot encoder
7. Menggabungkan dataset numerik dan kategorik
8. Membagi dataset menjadi train, test, valid
9. Melakukan standarisasi data
10. Meng-compile model
11. Melakukan hyperparameter tunning
12. Menjalankan model DNN
13. Melakukan prediksi
14. Menghitung akurasi dan klasifikasi report

Analisis

1. Akurasi yang didapat adalah 0.9/90%, artinya hasil prediksi sangat dekat dengan data asli.
2. Precision yang didapat adalah 0.9/90%, artinya hasil data dari feature-feature yang dipakai cukup relevan terhadap target
3. Recall yang didapat adalah 0.9/90%, artinya model DNN hampir tidak menghasilkan nilai negatif palsu dan hasil dari algoritma nya cukup relevan dengan target
4. F1 yang didapat adalah 0.9/90%, artinya model klasifikasi DNN yang dibuat sangat baik/hampir sempurna